stateNamesDict = {'A And N Islands': 'Andaman_&_Nicobar_Islands',
 'A.P': 'Andhra_Pradesh',
 'AJMER': '',
 'ANDHRA PRADESH': 'Andhra_Pradesh',
 'AP': 'Andhra_Pradesh',
 'ARUNACHAL PRADESH': 'Arunachal_Pradesh',
 'ASSAM': 'Assam',
 'Andhra Pradesh': 'Andhra_Pradesh',
 'Arunachal Pradesh': 'Arunachal_Pradesh',
 'Assam': 'Assam',
 'BIHAR': 'Bihar',
 'BOMBAY': '',
 'Bihar': 'Bihar',
 'CHANDIGARH': 'Chandigarh',
 'CHATISGARH': 'Chhattisgarh',
 'CHATTISGARH': 'Chhattisgarh',
 'CHHATTISGARH': 'Chhattisgarh',
 'Chandigarh': 'Chandigarh',
 'Chhattisgarh': 'Chhattisgarh',
 'D And N Haveli': 'Dadra_Nagar_&_Haveli',
 'DAMAN&DIU': 'Daman_&_Diu',
 'DELHI': 'Delhi',
 'Delhi': 'Delhi',
 'GJ': 'Gujarat',
 'GOA': 'Goa',
 'GOA - DAMAN & DIU': 'Goa,_Daman_&_Diu',
 'GOA,DAMAN&DIU': 'Goa,_Daman_&_Diu',
 'GUJARAT': 'Gujarat',
 'Goa': 'Goa',
 'Goa, Daman And Diu': 'Goa,_Daman_&_Diu',
 'Goa_Daman_&_Diu': 'Goa,_Daman_&_Diu',
 'Gujarat': 'Gujarat',
 'H.P': 'Himachal_Pradesh',
 'HARYANA': 'Haryana',
 'HIMACHAL PRADESH': 'Himachal_Pradesh',
 'HP': 'Himachal_Pradesh',
 'HYDERA': '',
 'Haryana': 'Haryana',
 'Himachal': 'Himachal_Pradesh',
 'Himachal Pradesh': 'Himachal_Pradesh',
 'J&K': 'Jammu_&_Kashmir',
 'JAMMU & KASHMIR': 'Jammu_&_Kashmir',
 'JAMMU +ACY- KASHMIR': 'Jammu_&_Kashmir',
 'JAMMU AND KASHMIR': 'Jammu_&_Kashmir',
 'JHARKHAND': 'Jharkhand',
 'Jammu And Kashmir': 'Jammu_&_Kashmir',
 'KARNATAKA': 'Karnataka',
 'KARNATAKA (MYSORE)': 'Mysore',
 'KARNATKA': 'Karnataka',
 'KARNATTAKA': 'Karnataka',
 'KERALA': 'Kerala',
 'KERELA': 'Kerala',
 'KUTCH': '',
 'Karnataka': 'Karnataka',
 'Kerala': 'Kerala',
 'M.P': 'Madhya_Pradesh',
 'M.P.': 'Madhya_Pradesh',
 'MADHAYA PARDESH': 'Madhya_Pradesh',
 'MADHYA BHARAT': '',
 'MADHYA PRADESH': 'Madhya_Pradesh',
 'MADRAS': 'Madras',
 'MAHARASHTRA': 'Maharashtra',
 'MANIPUR': 'Manipur',
 'MEGHALAYA': 'Meghalaya',
 'MHARASHTRA': 'Maharashtra',
 'MIZORAM': 'Mizoram',
 'MP': 'Madhya_Pradesh',
 'MT': '',
 'MYSORE': 'Mysore',
 'Madhya Pradesh': 'Madhya_Pradesh',
 'Madhyapradesh': 'Madhya_Pradesh',
 'Maharashtra': 'Maharashtra',
 'Manipur': 'Manipur',
 'Meghalaya': 'Meghalaya',
 'Mizoram': 'Mizoram',
 'Mysore': 'Mysore',
 'NAGALAND': 'Nagaland',
 'NCT OF DELHI': 'Delhi',
 'NCT of Delhi': 'Delhi',
 'NCT. of Delhi': 'Delhi',
 'Nagaland': 'Nagaland',
 'ORISSA': 'Odisha',
 'ORRISA': 'Odisha',
 'Orissa': 'Odisha',
 'PEPSU': '',
 'PODICHERRY': 'Puducherry',
 'PONDICHERRY': 'Puducherry',
 'PUNJAB': 'Punjab',
 'Pondicherry': 'Puducherry',
 'Punjab': 'Punjab',
 'RAJASTHAN': 'Rajasthan',
 'RJ': 'Rajasthan',
 'Rajasthan': 'Rajasthan',
 'SAURAS': '',
 'SIKKIM': 'Sikkim',
 'SOWRASHTRA': '',
 'T. COCHIN': '',
 'T.N': 'Tamil_Nadu',
 'TAMIL NADU': 'Tamil_Nadu',
 'TAMIL NADU (MADRAS)': 'Madras',
 'TAMILNADU': 'Tamil_Nadu',
 'TRIPURA': 'Tripura',
 'Tamil Nadu': 'Tamil_Nadu',
 'Tamilnadu': 'Tamil_Nadu',
 'Telangana': 'Telangana',
 'Tripura': 'Tripura',
 'U.P': 'Uttar_Pradesh',
 'U.T.DELHI': 'Delhi',
 'UP': 'Uttar_Pradesh',
 'UTTAR PARADESH': 'Uttar_Pradesh',
 'UTTAR PARDESH': 'Uttar_Pradesh',
 'UTTAR PRADESH': 'Uttar_Pradesh',
 'UTTARAKHAND': 'Uttarakhand',
 'UTTARANCHAL': 'Uttarakhand',
 'Uttar Pradesh': 'Uttar_Pradesh',
 'VP': '',
 'W.B': 'West_Bengal',
 'WB': 'West_Bengal',
 'WEST BENGAL': 'West_Bengal',
 'West Bengal': 'West_Bengal',
 'a & n islands': 'Andaman_&_Nicobar_Islands',
 'a and n islands': 'Andaman_&_Nicobar_Islands',
 'a.p': 'Andhra_Pradesh',
 'ajmer': '',
 'andaman & nicob': 'Andaman_&_Nicobar_Islands',
 'andaman & nicobar island': 'Andaman_&_Nicobar_Islands',
 'andaman & nicobar islands': 'Andaman_&_Nicobar_Islands',
 'andaman and nicobar islands': 'Andaman_&_Nicobar_Islands',
 'andhara_pradesh': 'Andhra_Pradesh ',
 'andhra pradesh': 'Andhra_Pradesh',
 'andhra_pradesh': 'Andhra_Pradesh',
 'ap': 'Andhra_Pradesh',
 'arunachal': 'Arunachal_Pradesh',
 'arunachal prade': 'Arunachal_Pradesh',
 'arunachal pradesh': 'Arunachal_Pradesh',
 'arunachal_pradesh': 'Arunachal_Pradesh',
 'assam': 'Assam',
 'bihar': 'Bihar',
 'bombay': '',
 'chandigarh': 'Chandigarh',
 'chatisgarh': 'Chhattisgarh',
 'chattisgarh': 'Chhattisgarh',
 'chhattisgarh': 'Chhattisgarh',
 'd & n haveli': 'Dadra_Nagar_&_Haveli',
 'd and n haveli': 'Dadra_Nagar_&_Haveli',
 'dadra & nagar h': 'Dadra_Nagar_&_Haveli',
 'dadra & nagar haveli': 'Dadra_Nagar_&_Haveli',
 'dadra and nagar haveli': 'Dadra_Nagar_&_Haveli',
 'dadra nagar & haveli': 'Dadra_Nagar_&_Haveli',
 'daman & diu': 'Daman_&_Diu',
 'daman&diu': 'Daman_&_Diu',
 'delhi': 'Delhi',
 'gj': 'Gujarat',
 'goa': 'Goa',
 'goa - daman & diu': 'Goa,_Daman_&_Diu',
 'goa daman & diu': 'Goa,_Daman_&_Diu',
 'goa, daman & diu': 'Goa,_Daman_&_Diu',
 'goa, daman and diu': 'Goa,_Daman_&_Diu',
 'goa,daman&diu': 'Goa,_Daman_&_Diu',
 'goa_daman_&_diu': 'Goa,_Daman_&_Diu',
 'goa_daman_and_diu': 'Goa,_Daman_&_Diu',
 'gujarat': 'Gujarat',
 'gujrat': 'Gujarat',
 'h.p': 'Himachal_Pradesh',
 'haryana': 'Haryana',
 'himachal': 'Himachal_Pradesh',
 'himachal prades': 'Himachal_Pradesh',
 'himachal pradesh': 'Himachal_Pradesh',
 'himachal_pradesh': 'Himachal_Pradesh',
 'hp': 'Himachal_Pradesh',
 'hydera': '',
 'j&k': 'Jammu_&_Kashmir',
 'jammu & kashmir': 'Jammu_&_Kashmir',
 'jammu +acy- kashmir': 'Jammu_&_Kashmir',
 'jammu _ kashmir': 'Jammu_&_Kashmir',
 'jammu and kashmir': 'Jammu_&_Kashmir',
 'jammu_&_kashmir': 'Jammu_&_Kashmir',
 'jammu_kashmir': 'Jammu_&_Kashmir',
 'jharkhand': 'Jharkhand',
 'karnataka': 'Karnataka',
 'karnataka (mysore)': 'Mysore',
 'karnatka': 'Karnataka',
 'karnattaka': 'Karnataka',
 'kerala': 'Kerala',
 'kerela': 'Kerala',
 'kerla': 'Kerala',
 'kutch': '',
 'l m and a islands': 'Lakshadweep',
 'laccadive minicoy and amindivi islands': 'Lakshadweep',
 'laccadive, minicoy and amindivi islands': 'Lakshadweep',
 'lakshadeep': 'Lakshadweep',
 'lakshadweep': 'Lakshadweep',
 'm.p': 'Madhya_Pradesh',
 'm.p.': 'Madhya_Pradesh',
 'madhaya pardesh': 'Madhya_Pradesh',
 'madhya bharat': '',
 'madhya pradesh': 'Madhya_Pradesh',
 'madhya_pradesh': 'Madhya_Pradesh',
 'madhyapradesh': 'Madhya_Pradesh',
 'madras': 'Madras',
 'maharashtra': 'Maharashtra',
 'manipur': 'Manipur',
 'meghalaya': 'Meghalaya',
 'mharashtra': 'Maharashtra',
 'mizoram': 'Mizoram',
 'mp': 'Madhya_Pradesh',
 'mt': '',
 'mysore': 'Mysore',
 'nagaland': 'Nagaland',
 'national capital': 'Delhi',
 'national capital territor': 'Delhi',
 'national capital territory of delhi': 'Delhi',
 'national_capital_territory_of_delhi': 'Delhi',
 'nct of delhi': 'Delhi',
 'nct. of delhi': 'Delhi',
 'odisha': 'Odisha',
 'orissa': 'Odisha',
 'orrisa': 'Odisha',
 'pepsu': '',
 'podicherry': 'Puducherry',
 'pondicherry': 'Puducherry',
 'puducherry': 'Puducherry',
 'punjab': 'Punjab',
 'rajasthan': 'Rajasthan',
 'rj': 'Rajasthan',
 'sauras': '',
 'sikkim': 'Sikkim',
 'sowrashtra': '',
 't. cochin': '',
 't.n': 'Tamil_Nadu',
 'tamil nadu': 'Tamil_Nadu',
 'tamil nadu (madras)': 'Madras',
 'tamil_nadu': 'Tamil_Nadu',
 'tamilnadu': 'Tamil_Nadu',
 'telangana': 'Telangana',
 'tripura': 'Tripura',
 'u.p': 'Uttar_Pradesh',
 'u.t.delhi': 'Delhi',
 'up': 'Uttar_Pradesh',
 'uttar paradesh': 'Uttar_Pradesh',
 'uttar pardesh': 'Uttar_Pradesh',
 'uttar pradesh': 'Uttar_Pradesh',
 'uttar_pradesh': 'Uttar_Pradesh',
 'uttarakhand': 'Uttarakhand',
 'uttaranchal': 'Uttarakhand',
 'uttarkhand': 'Uttarakhand',
 'vp': '',
 'w.b': 'West_Bengal',
 'wb': 'West_Bengal',
 'west bengal': 'West_Bengal',
 'west_bengal': 'West_Bengal'}